version: "3.8"
services:
  my_root:
    image: yelowduck/my_root
    container_name: my_root
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'my_bd'

    restart: always
    ports:
      - "3306:3306"

  my_postgres:
    container_name: my_postgres
    image: yelowduck/my_postgres
    restart: always
    ports:
      - "5432:5432"

  skript:
    build: ./Test/
#    image: yelowduck/my_skript
    container_name: skript
    command: sh -c "sleep 30s; python Test_migration.py"
    depends_on:
      - my_root
      - my_postgres


networks:
    default:
      name: self_network
      driver: bridge